<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>10</LangVersion>
    <AssemblyName>Jumpscare</AssemblyName>
    <RootNamespace>Jumpscare</RootNamespace>
    <Version>1.1.0</Version>
    <RainWorldDir>C:\Program Files (x86)\Steam\steamapps\common\Rain World</RainWorldDir>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx" HintPath="$(RainWorldDir)\BepInEx\core\BepInEx.dll" Private="false" />
    <Reference Include="Assembly-CSharp" HintPath="$(RainWorldDir)\BepInEx\utils\PUBLIC-Assembly-CSharp.dll" Private="false" />
    <Reference Include="HOOKS-Assembly-CSharp" HintPath="$(RainWorldDir)\BepInEx\plugins\HOOKS-Assembly-CSharp.dll" Private="false" />
    <Reference Include="MonoMod.RuntimeDetour" HintPath="$(RainWorldDir)\BepInEx\core\MonoMod.RuntimeDetour.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(RainWorldDir)\RainWorld_Data\Managed\UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(RainWorldDir)\RainWorld_Data\Managed\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.AudioModule" HintPath="$(RainWorldDir)\RainWorld_Data\Managed\UnityEngine.AudioModule.dll" Private="false" />
    <Reference Include="UnityEngine.ImageConversionModule" HintPath="$(RainWorldDir)\RainWorld_Data\Managed\UnityEngine.ImageConversionModule.dll" Private="false" />
    <Reference Include="UnityEngine.UnityWebRequestModule" HintPath="$(RainWorldDir)\RainWorld_Data\Managed\UnityEngine.UnityWebRequestModule.dll" Private="false" />
    <Reference Include="UnityEngine.UnityWebRequestAudioModule" HintPath="$(RainWorldDir)\RainWorld_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll" Private="false" />
  </ItemGroup>

</Project>
